name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # Optional: keep linting to catch issues
      - name: Run linter
        run: deno lint

      # Instead of running tests (none exist), just cache the main file
      - name: Cache dependencies
        run: deno cache index.ts
